### ISSUE TITLE
Output files in the input directory

### ISSUE THREAD

**Issue by unfunfunt** [Cosmoglobe/Commander#126]
[At line 3733 in comm_diffuse_comp_smod](https://github.com/Cosmoglobe/Commander/blob/3aa493eea78a1a51a7e788ee206a2bca6247fa06/commander3/src/comm_diffuse_comp_smod.f90#L3733) we seem to write an output file to the input directory, and not to the chains directory. This is an issue on clusters, where the input directory is sometimes mounted read-only for submitted jobs, and caused a crash on scinet. We should fix this by either removing this code (idk what it does) or fixing it to respect the output directory properly.

**Comment by hke** [comment]
This just looks like a debug file from Kristian. Can be commented out entirely.
