### ISSUE TITLE
Hard coded files in comm_n_qucov_mod.f90

### ISSUE THREAD

**Issue by unfunfunt** [Cosmoglobe/Commander#127]
[At line 149 in comm_n_qucov_mod.f90](https://github.com/Cosmoglobe/Commander/blob/3aa493eea78a1a51a7e788ee206a2bca6247fa06/commander3/src/comm_n_qucov_mod.f90#L149) we have three options for noisefiles, all of which require that the files be stored in a directory called 'data'. Each case seems to do the same thing anyway, so I'm not sure what this code is designed to do or if it is useful at all.

**Comment by hke** [comment]
This is also some left-over debug statements. Lines 149-159 can just be removed.

**Comment by unfunfunt** [comment]
Removed in my latest commit
