### ISSUE TITLE
Writing huffman compressed data from Commander simulations runs

### ISSUE THREAD

**Issue by dncnwtts** [Cosmoglobe/Commander#128]
Currently, what I've implemented in the `write_huffman` branch just writes uncompressed data, and I have written a python script that will compress the uncompressed data. It would be nice if this were done in Commander, but several things need to be done:

- Create the huffman tree structure in commander
- Encode the symbols as a binary string
- Write the tree and the symbols into the output hdf5 file.

The first two just require fixing my buggy implementation, but the last one requires deleting a dataset in the existing hdf5 file, which as far as I can tell, is not actually implemented in the Fortran implementation of the hdf library.

**Comment by unfunfunt** [comment]
This was deemed a stupid idea
