### ISSUE TITLE
Issue with initializing the synchrotron component

### ISSUE THREAD

**Issue by hermda02** [Cosmoglobe/Commander#134]
Error when attempting to initialize the synchrotron component:

` FITSIO Error Status =         104 : could not open the named file
 failed to find or open the following file: (ffopen)

 /mn/stornext/u3/hke/xsan/commander3/BP9/data/0.4-Haslam

`

It appears that in the `devel` version, Commander is attempting to read the band named 0.4-Haslam as a file as opposed to using that band as a prior for the synchrotron monopole.

**Comment by hermda02** [comment]
This appears to happen when removing the Haslam band while attempting to initialize the synchrotron component.

**Comment by unfunfunt** [comment]
This should be changed to improving the error message in this case
