### ISSUE TITLE
Memory corruption leading to segfaults

### ISSUE THREAD

**Issue by eirikgje** [Cosmoglobe/Commander#52]
Currently, the devel branch cannot be run with TOD_NUM_BP_PROPOSALS_PER_ITER >0 - it has to be set to 0, or segfaults will result.

Statement from HKE:
"Yes, I don't think it's worth debugging this quite yet. Been there, done that.. :slightly_smiling_face: What happens is actually that polres suddenly changes from 3.14e-2 to -7.e-6 or something like that during the tod projection operator -- which has nothing at all to do with the polres variable. But with a very small and negative polres variable, the derived polangle indices goes completely crazy, and the code crashes with a segfault. But that's just a symptom -- the actual problem is a memory corruption bug much further down the line. And the typical culprit for these types of memory corruption errors is passing wrong array sizes to external libraries, which do not perform array boundary checks. And by far the most typical offender is HDF. That's why I would like to have an HDF version with boundary checking turned on. That should hopefully let us see which array is the problematic one. So, my prediction is that this is eventually going to be traced down to some read_hdf call (or similar) with incorrect array size, dimension or type."

**Comment by eirikgje** [comment]
Assigning @maksymbrl because the current next step is to get debug flags to work with HDF.

**Comment by unfunfunt** [comment]
This is closed due to no one remembering anything about it
