### ISSUE TITLE
Connect GitHub wiki page and BeyondPlanck-Commander documentation page

### ISSUE THREAD

**Issue by trygvels** [Cosmoglobe/Commander#7]
Title should be descriptive enough. Link them somehow?

**Comment by trygvels** [comment]
This is the page I am talking about;
https://docs.beyondplanck.science/#/parameters/intro

**Comment by maksymbrl** [comment]
I have ported BP docs into GitHub pages:
https://cosmoglobe.github.io/Commander/
The sources can be found here:
https://github.com/Cosmoglobe/Commander/tree/devel/docs
With this, I am closing the issue.
