### ISSUE TITLE
comm_hdf_mod cmake compilation issue

### ISSUE THREAD

**Issue by hermda02** [Cosmoglobe/Commander#80]
It seems that new commits to comm_hdf_mod causes compilation issues when trying to build with cmake.

**Comment by unfunfunt** [comment]
Can you attach the log of the compiler output so we can see the issue?

**Comment by hermda02** [comment]
From cmake:
`daniher@owl31 Commander]$ bash ./install_owls.sh 
You are on owl31.uio.no
(Re)loaded the following modules:
Currently Loaded Modulefiles:
  1) gnu                                2) git/2.30.1                         3) Intel_parallel_studio/2018/3.051

Checking for 'build' directory.
/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135 exists! Proceeding...
-- ===============================================================
-- Welcome to automatic Commander3 installer!
-- Issued under: GNU GPLv3 license
-- Official repo: https://github.com/Cosmoglobe/Commander
-- Documentation: https://docs.beyondplanck.science
-- Forum: https://forums.beyondplanck.science/
-- ===============================================================
-- Scanning your system. Please, wait a moment...
-- ---------------------------------------------------------------
-- SUMMARY ON COMPILERS:
-- ---------------------------------------------------------------
-- Your system is: Linux, Linux-3.10.0-1160.24.1.el7.x86_64
-- Fortran Compiler is: /astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/ifort
-- C Compiler is: /astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icc
-- C++ Compiler is: /astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc
-- Commander3 configuration is: RelWithDebInfo. Compiler flags to be applied:
-- -O2;-g;-traceback;-DNDEBUG;-parallel;-qopenmp;-qopt-matmul;-C;-assume;byterecl;-heap-arrays;16384;-fpe0;-fPIC ;
-- owl31.uio.no
-- Linux x86_64 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Mar 25 21:21:56 UTC 2021
-- Unknown AMD family | 64 core AMD EPYC 7551 32-Core Processor
-- ---------------------------------------------------------------
-- SUMMARY ON INSTALLATION:
-- ---------------------------------------------------------------
-- Projects will be downloaded into: /mn/stornext/d14/Planck1/daniher/Commander/downloads
-- Projects will be installed into: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install
-- ---------------------------------------------------------------
-- Looking for packages...
-- math (m) libraries are: /usr/lib64/libm.so
-- dl libs are: dl
-- ---------------------------------------------------------------
-- MPI Libs Path: /net/alruba2.uio.no/mn/alruba2/astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib/libmpifort.so;/net/alruba2.uio.no/mn/alruba2/astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib/release_mt/libmpi.so;/net/alruba2.uio.no/mn/alruba2/astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib/libmpigi.a;/usr/lib64/libdl.so;/usr/lib64/librt.so;/usr/lib64/libpthread.so
-- MPI Include Path: /net/alruba2.uio.no/mn/alruba2/astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/include
-- MPI Compile Options are: 
-- MPI Link options are: -Xlinker --enable-new-dtags -Xlinker -rpath -Xlinker /astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib/release_mt -Xlinker -rpath -Xlinker /astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mpi/intel64/lib -Xlinker -rpath -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib/release_mt -Xlinker -rpath -Xlinker /opt/intel/mpi-rt/2017.0.0/intel64/lib
-- THREADS Libs Path: -lpthread
-- ---------------------------------------------------------------
-- Found OpenMP_C: -qopenmp  
-- Found OpenMP_CXX: -qopenmp  
-- Found OpenMP_Fortran: -qopenmp  
-- Found OpenMP: TRUE   
-- OPENMP Fortran LIBRARIES are: /astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libiomp5.so
-- ---------------------------------------------------------------
-- Could NOT find ZLIB: Found unsuitable version "1.2.7", but required is at least "1.2.11" (found /usr/lib64/libz.so)
-- Required version -- 1.2.11 -- will be compiled from source.
-- ZLIB LIBRARIES will be: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libz.so
-- ZLIB INCLUDE DIRS will be: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/include
-- ---------------------------------------------------------------
-- LIBAEC LIBRARIES will be: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libaec.so;/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libsz.so
-- LIBAEC INCLUDE DIRS will be: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/include
-- ---------------------------------------------------------------
-- CFITSIO LIBRARIES will be: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libcfitsio.a
-- CFITSIO INCLUDE DIRS will be: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/include/
-- ---------------------------------------------------------------
-- A library with LAPACK API found.
-- BLAS LINKER FLAGS:   
-- BLAS LIBRARIES:      /astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so;/astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so;/astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_core.so;/astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libiomp5.so;-lpthread;-lm;-ldl
-- LAPACK LINKER FLAGS: 
-- LAPACK LIBRARIES:    /astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so;/astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so;/astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin/libmkl_core.so;/astro/local/opt/Intel/compilers_and_libraries_2018.3.222/linux/compiler/lib/intel64_lin/libiomp5.so;-lpthread;-lm;-ldl;-lpthread;-lm;-ldl
-- ---------------------------------------------------------------
-- Missing component - DOUBLE - will be compiled from source
-- Missing component - DOUBLE_THREADS - will be compiled from source
-- Missing component - FLOAT - will be compiled from source
-- Missing component - FLOAT_THREADS - will be compiled from source
-- Missing component - FLOAT_OPENMP - will be compiled from source
-- Missing component - FLOAT_MPI - will be compiled from source
-- ---------------------------------------------------------------
-- Missing component -- Fortran -- will be compiled from source.
-- HDF5 Fortran LIBRARIES will be: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libhdf5_hl_fortran.a;/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libhdf5_hl_f90cstub.a;/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libhdf5_fortran.a;/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libhdf5_f90cstub.a;/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libhdf5_hl.a;/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libhdf5.a;/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libz.so;/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/lib/libsz.so
-- HDF5 Fortran INCLUDE DIRS will be: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/include;/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/include/static
-- ---------------------------------------------------------------
-- Missing component - Fortran - will be compiled from source
-- HEALPIX LIBRARIES will be: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/healpix/lib/libsharp.a;/mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/healpix/lib/libhealpix.a
-- ---------------------------------------------------------------
-- Finished looking for packages.
-- ---------------------------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135
[  0%] Built target mpi
[  0%] Built target openmp
[  0%] Built target tempita
[  0%] Built target curl
[  0%] Built target mbedtls
[  0%] Built target doxygen
[  0%] Built target libssh2
[  1%] Built target comm_system_backend
[  1%] Built target required_libraries
[  5%] Built target fftw
[  6%] Performing update step for 'libaec_src'
[  7%] Performing configure step for 'cfitsio'
[  7%] Built target blas
[ 12%] Built target zlib
[ 12%] Performing configure step for 'fftw_double'
[ 13%] Performing configure step for 'fftw_float'
[ 14%] No configure step for 'libaec_src'
[ 14%] No build step for 'libaec_src'
[ 15%] No install step for 'libaec_src'
[ 15%] Completed 'libaec_src'
[ 16%] Built target libaec_src
[ 16%] Performing configure step for 'libaec_static'
[ 16%] Performing configure step for 'libaec_shared'
-- libaec_shared configure command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/libaec_shared-configure-*.log
-- libaec_static configure command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/libaec_static-configure-*.log
[ 17%] Performing build step for 'libaec_shared'
[ 18%] Performing build step for 'libaec_static'
-- libaec_shared build command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/libaec_shared-build-*.log
-- libaec_static build command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/libaec_static-build-*.log
[ 18%] Performing install step for 'libaec_shared'
[ 19%] Performing install step for 'libaec_static'
-- libaec_static install command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/libaec_static-install-*.log
-- libaec_shared install command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/libaec_shared-install-*.log
[ 20%] Completed 'libaec_static'
[ 21%] Completed 'libaec_shared'
[ 23%] Built target libaec_static
[ 26%] Built target libaec_shared
[ 26%] Built target libaec
[ 26%] Performing configure step for 'hdf5'
-- cfitsio configure command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/cfitsio-configure-*.log
[ 27%] Performing build step for 'cfitsio'
-- cfitsio build command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/cfitsio-build-*.log
[ 27%] Performing install step for 'cfitsio'
-- cfitsio install command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/cfitsio-install-*.log
[ 28%] Completed 'cfitsio'
[ 30%] Built target cfitsio
[ 31%] Performing configure step for 'healpix'
-- healpix configure command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/healpix-configure-*.log
[ 31%] Performing build step for 'healpix'
-- healpix build command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/healpix-build-*.log
[ 32%] Performing install step for 'healpix'
-- hdf5 configure command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/hdf5-configure-*.log
[ 33%] Performing build step for 'hdf5'
-- healpix install command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/healpix-install-*.log
[ 33%] Completed 'healpix'
[ 35%] Built target healpix
[ 35%] Performing update step for 'camb'
[ 35%] Performing configure step for 'camb'
-- Found OpenMP_Fortran: -qopenmp  
-- Found OpenMP: TRUE  found components: Fortran 
-- A library with LAPACK API found.
-- Submodule update
-- Configuring done
-- Generating done
-- Build files have been written to: /mn/stornext/d14/Planck1/daniher/Commander/downloads/camb/src/camb-build
[ 36%] Performing build step for 'camb'
[ 26%] Built target forutils
[ 28%] Building Fortran object CMakeFiles/camb.dir/fortran/writefits.f90.o
Cannot disable Fortran error message 7002
/mn/stornext/d14/Planck1/daniher/Commander/downloads/camb/src/camb/fortran/writefits.f90(7): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [HEAD_FITS]
  use head_fits, ONLY : add_card 
------^
Cannot disable Fortran error message 7002
/mn/stornext/d14/Planck1/daniher/Commander/downloads/camb/src/camb/fortran/writefits.f90(8): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [FITSTOOLS]
  use fitstools, only : write_asctab
------^
Cannot disable Fortran error message 6406
/mn/stornext/d14/Planck1/daniher/Commander/downloads/camb/src/camb/fortran/writefits.f90(99): error #6406: Conflicting attributes or multiple declaration of name.   [WRITE_ASCTAB]
  call write_asctab (allcl, lmx, 4, header, nlheader, Clsfile)
-------^
Cannot disable Fortran error message 6580
/mn/stornext/d14/Planck1/daniher/Commander/downloads/camb/src/camb/fortran/writefits.f90(7): error #6580: Name in only-list does not exist or is not accessible.   [ADD_CARD]
  use head_fits, ONLY : add_card 
------------------------^
Cannot disable Fortran error message 6580
/mn/stornext/d14/Planck1/daniher/Commander/downloads/camb/src/camb/fortran/writefits.f90(8): error #6580: Name in only-list does not exist or is not accessible.   [WRITE_ASCTAB]
  use fitstools, only : write_asctab
------------------------^
compilation aborted for /mn/stornext/d14/Planck1/daniher/Commander/downloads/camb/src/camb/fortran/writefits.f90 (code 1)
gmake[5]: *** [CMakeFiles/camb.dir/fortran/writefits.f90.o] Error 1
gmake[4]: *** [CMakeFiles/camb.dir/all] Error 2
gmake[3]: *** [all] Error 2
gmake[2]: *** [../downloads/camb/src/camb-stamp/camb-build] Error 2
gmake[1]: *** [CMakeFiles/camb.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
-- fftw_double configure command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/fftw_double-configure-*.log
[ 37%] Performing build step for 'fftw_double'
-- fftw_float configure command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/fftw_float-configure-*.log
[ 37%] Performing build step for 'fftw_float'
CMake Error at /mn/stornext/d14/Planck1/daniher/Commander/downloads/hdf5/src/hdf5-stamp/hdf5-build-RelWithDebInfo.cmake:49 (message):
  Command failed: 2

   '/usr/bin/gmake'

  See also

    /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/hdf5-build-*.log


gmake[2]: *** [../downloads/hdf5/src/hdf5-stamp/hdf5-build] Error 1
gmake[1]: *** [CMakeFiles/hdf5.dir/all] Error 2
-- fftw_double build command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/fftw_double-build-*.log
[ 37%] Performing install step for 'fftw_double'
-- fftw_float build command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/fftw_float-build-*.log
[ 38%] Performing install step for 'fftw_float'
-- fftw_double install command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/fftw_double-install-*.log
[ 39%] Completed 'fftw_double'
[ 42%] Built target fftw_double
-- fftw_float install command succeeded.  See also /mn/stornext/d14/Planck1/daniher/Commander/build_owl3135/install/logs/fftw_float-install-*.log
[ 42%] Completed 'fftw_float'
[ 44%] Built target fftw_float
gmake: *** [all] Error 2
`

**Comment by hermda02** [comment]
This has changed `comm_hdf_mod`, so when trying to compile with make:
`[daniher@owl29 Commander]$ make
make[1]: Entering directory `/mn/stornext/d14/Planck1/daniher/Commander/commander3/src'
mpiifort -fpe0 -march=native -g -O2 -traceback -assume byterecl -heap-arrays 16384 -qopenmp -parallel -lmkl    -I../../build_owl2930/install/healpix/include -I../../build_owl2930/install/include/shared -I../../build_owl2930/install/mod -c comm_hdf_mod.f90
mpiifort -fpe0 -march=native -g -O2 -traceback -assume byterecl -heap-arrays 16384 -qopenmp -parallel -lmkl    -I../../build_owl2930/install/healpix/include -I../../build_owl2930/install/include/shared -I../../build_owl2930/install/mod -c comm_map_mod.f90
mpiifort -fpe0 -march=native -g -O2 -traceback -assume byterecl -heap-arrays 16384 -qopenmp -parallel -lmkl    -I../../build_owl2930/install/healpix/include -I../../build_owl2930/install/include/shared -I../../build_owl2930/install/mod -c comm_4D_map_mod.f90
mpiifort -fpe0 -march=native -g -O2 -traceback -assume byterecl -heap-arrays 16384 -qopenmp -parallel -lmkl    -I../../build_owl2930/install/healpix/include -I../../build_owl2930/install/include/shared -I../../build_owl2930/install/mod -c comm_conviqt_mod.f90
mpiifort -fpe0 -march=native -g -O2 -traceback -assume byterecl -heap-arrays 16384 -qopenmp -parallel -lmkl    -I../../build_owl2930/install/healpix/include -I../../build_owl2930/install/include/shared -I../../build_owl2930/install/mod -c comm_B_mod.f90
mpiifort -fpe0 -march=native -g -O2 -traceback -assume byterecl -heap-arrays 16384 -qopenmp -parallel -lmkl    -I../../build_owl2930/install/healpix/include -I../../build_owl2930/install/include/shared -I../../build_owl2930/install/mod -c comm_B_bl_mod.f90
mpiifort -fpe0 -march=native -g -O2 -traceback -assume byterecl -heap-arrays 16384 -qopenmp -parallel -lmkl    -I../../build_owl2930/install/healpix/include -I../../build_owl2930/install/include/shared -I../../build_owl2930/install/mod -c comm_beam_mod.f90
mpiifort -fpe0 -march=native -g -O2 -traceback -assume byterecl -heap-arrays 16384 -qopenmp -parallel -lmkl    -I../../build_owl2930/install/healpix/include -I../../build_owl2930/install/include/shared -I../../build_owl2930/install/mod -c comm_tod_orbdipole_mod.f90
mpiifort -fpe0 -march=native -g -O2 -traceback -assume byterecl -heap-arrays 16384 -qopenmp -parallel -lmkl    -I../../build_owl2930/install/healpix/include -I../../build_owl2930/install/include/shared -I../../build_owl2930/install/mod -c comm_tod_mod.f90
comm_tod_mod.f90(52): error #6457: This derived type name has not been declared.   [BYTE_POINTER]
     type(byte_pointer), allocatable, dimension(:)    :: zdiode         ! pointers to the compressed undeifferenced diode data, len (ndiode)
----------^
comm_tod_mod.f90(402): error #6404: This name does not have a type, and must have an explicit type.   [PIX]
          call huffman_decode2_int(self%scans(i)%hkey, self%scans(i)%d(j)%pix(l)%p, pix)
--------------------------------------------------------------------------^
comm_tod_mod.f90(402): error #6460: This is not a field name that is defined in the encompassing structure.   [P]
          call huffman_decode2_int(self%scans(i)%hkey, self%scans(i)%d(j)%pix(l)%p, pix)
---------------------------------------------------------------------------------^
comm_tod_mod.f90(402): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [P]
          call huffman_decode2_int(self%scans(i)%hkey, self%scans(i)%d(j)%pix(l)%p, pix)
---------------------------------------------------------------------------------^
comm_tod_mod.f90(764): error #6404: This name does not have a type, and must have an explicit type.   [PSI]
       allocate(self%d(i)%psi(nhorn), self%d(i)%pix(nhorn))
--------------------------^
comm_tod_mod.f90(805): error #7976: An allocatable dummy argument may only be argument associated with an allocatable actual argument.   [P]
           call read_hdf_opaque(file, slabel // "/" // trim(field) // "/pix" // achar(j+64),  self%d(i)%pix(j)%p)
---------------------------------------------------------------------------------------------------------------^
comm_tod_mod.f90(805): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [P]
           call read_hdf_opaque(file, slabel // "/" // trim(field) // "/pix" // achar(j+64),  self%d(i)%pix(j)%p)
---------------------------------------------------------------------------------------------------------------^
comm_tod_mod.f90(806): error #7976: An allocatable dummy argument may only be argument associated with an allocatable actual argument.   [P]
           call read_hdf_opaque(file, slabel // "/" // trim(field) // "/psi" // achar(j+64),  self%d(i)%psi(j)%p)
---------------------------------------------------------------------------------------------------------------^
comm_tod_mod.f90(806): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [P]
           call read_hdf_opaque(file, slabel // "/" // trim(field) // "/psi" // achar(j+64),  self%d(i)%psi(j)%p)
---------------------------------------------------------------------------------------------------------------^
comm_tod_mod.f90(810): error #7976: An allocatable dummy argument may only be argument associated with an allocatable actual argument.   [P]
           call read_hdf_opaque(file, slabel // "/" // trim(field) // "/pix",  self%d(i)%pix(j)%p)
------------------------------------------------------------------------------------------------^
comm_tod_mod.f90(810): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [P]
           call read_hdf_opaque(file, slabel // "/" // trim(field) // "/pix",  self%d(i)%pix(j)%p)
------------------------------------------------------------------------------------------------^
comm_tod_mod.f90(811): error #7976: An allocatable dummy argument may only be argument associated with an allocatable actual argument.   [P]
           call read_hdf_opaque(file, slabel // "/" // trim(field) // "/psi",  self%d(i)%psi(j)%p)
------------------------------------------------------------------------------------------------^
comm_tod_mod.f90(811): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [P]
           call read_hdf_opaque(file, slabel // "/" // trim(field) // "/psi",  self%d(i)%psi(j)%p)
------------------------------------------------------------------------------------------------^
comm_tod_mod.f90(962): error #6404: This name does not have a type, and must have an explicit type.   [ZDIODE]
             allocate(self%d(i)%zdiode(ndiode))
--------------------------------^
comm_tod_mod.f90(1966): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [P]
      call huffman_decode2_int(self%scans(scan)%hkey, self%scans(scan)%d(det)%pix(i)%p,  pix(:,i))
-------------------------------------------------------------------------------------^
comm_tod_mod.f90(1967): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [P]
      call huffman_decode2_int(self%scans(scan)%hkey, self%scans(scan)%d(det)%psi(i)%p,  psi(:,i), imod=self%npsi-1)
-------------------------------------------------------------------------------------^
comm_tod_mod.f90(2036): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [P]
        call huffman_decode2_sp(self%scans(scan)%todkey, self%scans(scan)%d(det)%zdiode(i)%p, diodes(:,i))
-------------------------------------------------------------------------------------------^
comm_tod_mod.f90(2060): error #6634: The shape matching rules of actual arguments and dummy arguments have been violated.   [P]
      call huffman_decode2_int(self%scans(scan)%hkey, self%scans(scan)%d(det)%pix(1)%p, pix)
-------------------------------------------------------------------------------------^
compilation aborted for comm_tod_mod.f90 (code 1)
make[1]: *** [comm_tod_mod.o] Error 1
make[1]: Leaving directory `/mn/stornext/d14/Planck1/daniher/Commander/commander3/src'
make: *** [commander] Error 2`

**Comment by hermda02** [comment]
Simply replacing `comm_hdf_mod` with the file currently in the `adc` branch fixes the compilation issue.

**Comment by unfunfunt** [comment]
I'm just confused about why comm_hdf_mode gets overwritten at all. It doesn't look like there is anything in the cmake output about it

**Comment by dncnwtts** [comment]
My understanding of the comm_hdf_mod.f90 files is that tempita is used to
turn comm_hdf_mod.f90.in into the new file, so that basically, no commits
should be made directly to the comm_hdf_mod.f90 file. I'm not sure why this
is, just that it "is".

**Comment by maksymbrl** [comment]
@unfunfunt, the production of `comm_hdf_mod.f90` from `comm_hdf_mod.f90.in`was present in Makefile long before CMake, and the latter just tries to repeat the Makefile's steps. 

Let us take a look at them:
https://github.com/Cosmoglobe/Commander/blob/devel/Makefile
https://github.com/Cosmoglobe/Commander/blob/devel/commander3/src/Makefile
First has the line:
```
106 export TEMPITA := "$(TOPDIR)/commander3/python/tempita_proc.py"
```
which introduces variable `TEMPITA`, while the second:
```
166 %.f90 : %.f90.in
167 	   $(TEMPITA) < "$<" > "$@"
```
uses it to produce `*.f90` files from `*.f90.in`. The relevant parts for CMake code are here:
https://github.com/Cosmoglobe/Commander/blob/devel/cmake/required_libraries.cmake
where the code is:
```
add_custom_target(tempita ALL "")
set(comm_hdf_mod "${COMMANDER3_SOURCE_DIR}/comm_hdf_mod.f90")
# running python command at configure time
89 execute_process(
90  	COMMAND ${TEMPITA_DIR}/tempita_proc.py < $< > $@
91	INPUT_FILE ${comm_hdf_mod}.in
92	OUTPUT_FILE ${comm_hdf_mod}
93	)
```
All in all, the `comm_hdfd_mod.f90` will be overwritten regardless of the chosen compilation procedure. As to "why", I do not really understand myself either -- the idea was just to repeat whatever we had in Makefile back then. From the `comm_hdf_mod.f90.in`:
```
! Due to the extreme amount of redundancy in hdf_mod, it is now generated
! by using the handy tempita template language. All the machinery for
! doing this is included in the repository, so this should just work.
```
And this is the only explanation I have.

And yes, as @dncnwtts has pointed out, nothing should be committed to `comm_hdf_mod.f90` as the changes will be overwritten by tempita. Use `comm_hdf_mod.f90.in` instead. 

@hermda02, as I see it, your issues are connected to compiling `CAMB` and `HDF5` libraries. The first one has our own `CMake` script so it is not surprising there are bugs in it (although the last time I checked it worked, but only with `Intel` compilers, I have yet to incorporate GNU), while I am not entirely sure why the second one crushed as well.  What I found even weirder is the fact that `devel` branch does not have `CAMB` as its dependency (although the necessary files are present),  while it is included inside `adc`branch. Perhaps it was overwritten during one of the merges?

**Comment by hermda02** [comment]
When I compile with the Makefile, it doesn't look like `comm_hdf_mod` gets overwritten. I can try to change the offending lines (definition of `byte_pointer`) to match `devel` to see if that fixes the issues.

I would also like to know if this issue is reproducible for anyone else. I'll see if I can get Duncan to test that for me.

**Comment by maksymbrl** [comment]
@hermda02, I have tried to recompile it and have encountered exactly the same issue you had. However, CAMB and HDF5 compiled without any problem, so there is only an issue with `comm_hdf_mod.f90`. I think that somebody or something (e.g. `git merge/pull` to `adc` branch) just overwrote and committed the `comm_hdf_mod.f90` instead of `comm_hdf_mod.f90.in` and that is why it doesn't compile successfully.

Perhaps, when you compile with Makefile the `comm_hdf_mod.f90` is written only if it doesn't exist? I believe CMake is configured to overwrite it every time (although need to check it), so this is the main difference. In theory, it shouldn't matter though.

**Comment by hermda02** [comment]
If I `make clean; make`, things compile just fine on my end. I'm going to try changing `comm_hdf_mod.f90.in` and see if this fixes things.

**Comment by maksymbrl** [comment]
The `make clean; make` doesn't cut it for me though -- getting the same error. Also, there is the line on the terminal output:
```
".../commander/adc/commander3/python/tempita_proc.py" < "comm_hdf_mod.f90.in" > "comm_hdf_mod.f90"
mpiifort -fpe0 -march=native -g -O2 -traceback -assume byterecl -heap-arrays 16384 -qopenmp -parallel -lmkl    -I/.../Healpix_3.50/include -I/.../include -I/.../commander3/install/mod -c comm_hdf_mod.f90
```
which tells me after `make clean` the `comm_hdf_mod.f90` is getting regenerated again.

**Comment by hermda02** [comment]
I've made the proper adjustments to `comm_hdf_mod.f90.in` that fixes the compilation (both for the Makefile and cmake). Seems that there were a handful of changes to `comm_hdf_mod.f90` that were *not* included in the corresponding `.in` file. I'm testing now to make sure the code still functions as intended.
