### ISSUE TITLE
Merging burned-in chains

### ISSUE THREAD

**Issue by dncnwtts** [Cosmoglobe/Commander#88]
There doesn't seem to be an "easy" way (that I'm aware of) to take burned in instrument files from one experiment that was running independently and merge them together. It would be nice to do that since it takes a while for WMAP to burn in by itself.

Of course, if this functionality already exists, I retract the issue.

**Comment by hke** [comment]
Not sure what you mean by "burned in instrument files". Instrument files aren't updated, but only contain static information.

But if you're talking about the instrument parameters from different chain files then you can specify the chain file for each frequency band, at least. That's what I usually do during burn-in: Run separately one chain per band, fixing the signal model, and then merge things together using separate init chain files for each channel.

Hans Kristian



⁣Få BlueMail for Android ​

7. sep. 2021, 15:31 kl. 15:31 skrev Duncan Watts ***@***.***>:

**Comment by dncnwtts** [comment]
I see, I misunderstood the INIT_INSTRUMENT_FROM_HDF parameter, I was just
used to the "default" and "none" options, but of course you can specify the
hdf from a previously burned in set of instrument parameters.

Example:

INIT_INSTRUMENT_FROM_HDF      =
/mn/stornext/d16/cmbco/bp/dwatts/WMAP/backup.h5:6
