### ISSUE TITLE
Chain statistics files output

### ISSUE THREAD

**Issue by dncnwtts** [Cosmoglobe/Commander#90]
In Commander1, there was a file that would output statistics like chi_hiliat, chi_lolat, beta_mean, amp_mean, etc. I believe this was in line ~883 of commander.f90 of Commander1, it would be good to have something like this implemented in Commander3.

**Comment by dncnwtts** [comment]
Example:

[fg_ind_mean_no0001.txt](https://github.com/Cosmoglobe/Commander/files/7137189/fg_ind_mean_no0001.txt)

**Comment by unfunfunt** [comment]
Closed because this already existed
